feeds:
  - https://rss.cnn.com/rss/cnn_topstories.rss
  - https://feeds.apnews.com/rss/apf-topnews
  - https://www.npr.org/rss/rss.php?id=1001
  - https://www.seattletimes.com/feed/
  - https://www.wsj.com/xml/rss/3_7085.xml
  - https://www.thecentersquare.com/search/?f=rss&t=article&l=50
